version: '3.7'
services:
  service-1:
   build:
     context: /home/student/nbs-mentored-project/service-1
     dockerfile: Dockerfile     
   ports:
   - target: 5000
     published: 5000
     protocol: tcp
  service-2:
    build:
      context: /home/student/nbs-mentored-project/service-2     
      dockerfile: Dockerfile
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
  service-3:
   build:
     context: /home/student/nbs-mentored-project/service-3 
     dockerfile: Dockerfile
   ports:
   - target: 5002
     published: 5002
     protocol: tcp
  service-4:
   build:
     context: /home/student/nbs-mentored-project/service-4      
     dockerfile: Dockerfile
   ports:
   - target: 5003
     published: 5003
     protocol: tcp
